### PR TITLE
feat: Support React Server Components

### PR DESCRIPTION
**Pull request by Ayterx**

### CODE REVIEW

**Comment by Hacksore** [comment]
There is some [info here](https://phryneas.de/react-server-components-controversy) around what libs should do regarding RSCs.

This seems fine for now until there is a better solution 😅.

**Comment by Hacksore** [comment]
FWIW I tried `ssr: false` with dynamic import but RSC requires us to have the directive.

https://codesandbox.io/p/sandbox/react-skinview3d-next-esm-rsc-qrtvfp

**Comment by Ayterx** [comment]
Dynamic import won't fix it because the 'react-skinview3d' uses useEffect and other client functions. It's required to have the 'use client' directive. Reference: https://nextjs.org/docs/getting-started/react-essentials#when-to-use-server-and-client-components. Otherwise, you have to create a new file with the 'use client' expression:

/app
- page.tsx
- skin.tsx (with 'use client')

This commit fixes the issue, so you don't have to create a new file.

**Comment by Ayterx** [comment]
When will this be released?

**Pull request merged**
