### PR TITLE
Add prop for orbit controls

### PR DESCRIPTION
**Pull request by OxKitsune**
I needed a way to disable the orbit controls for a little side project I'm working on. I'm pretty sure this is enough but I'm new to react and I barely use js so please let me know if these changes are ok.

### CODE REVIEW

**Comment by Hacksore** [comment]
This looks good to me, thanks for the contribution.

**Comment by OxKitsune** [comment]
Could you deploy this to npm/yarn? and increment the version

**Comment by Hacksore** [comment]
@OxKitsune done and `1.4.0` is available, let me know if to works for you.

**Comment by OxKitsune** [comment]
Yes it works! Thank you so much!!

**Pull request merged**
